<?php
namespace App\Services;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
class SecureMessageAttachmentService{
public function store(?UploadedFile $file,bool $allowPdf=false):array{if(!$file)return [];$mime=$file->getMimeType();if($allowPdf&&$mime==='application/pdf')$path=$file->store('secure-messages','local');else{$ext=$mime==='image/png'?'png':'jpg';$path='secure-messages/'.Str::uuid().'.'.$ext;Storage::disk('local')->makeDirectory('secure-messages');$this->resize($file->getPathname(),Storage::disk('local')->path($path),$mime);}return ['attachment_disk'=>'local','attachment_path'=>$path,'attachment_name'=>$file->getClientOriginalName(),'attachment_mime'=>$mime,'attachment_size'=>Storage::disk('local')->size($path)];}
public function delete(array $a):bool{if(blank($a['attachment_path']??null))return true;$d=Storage::disk($a['attachment_disk']??'local');return !$d->exists($a['attachment_path'])||$d->delete($a['attachment_path']);}
private function resize(string $src,string $dest,string $mime):void{$size=@getimagesize($src);if(!$size||($size[0]*$size[1])>25000000)throw ValidationException::withMessages(['attachment'=>'The image dimensions are too large to process safely.']);$im=$mime==='image/png'?@imagecreatefrompng($src):@imagecreatefromjpeg($src);if(!$im)throw ValidationException::withMessages(['attachment'=>'The image could not be processed.']);if($mime==='image/jpeg'&&function_exists('exif_read_data')){$o=@exif_read_data($src)['Orientation']??1;$a=match($o){3=>180,6=>-90,8=>90,default=>0};if($a){$r=imagerotate($im,$a,0);imagedestroy($im);if(!$r)throw ValidationException::withMessages(['attachment'=>'The image orientation could not be corrected.']);$im=$r;}}$w=imagesx($im);$h=imagesy($im);$scale=min(1,2000/max($w,$h));$out=imagecreatetruecolor(max(1,(int)round($w*$scale)),max(1,(int)round($h*$scale)));if(!$out)throw ValidationException::withMessages(['attachment'=>'The image could not be resized.']);if($mime==='image/png'){imagealphablending($out,false);imagesavealpha($out,true);}imagecopyresampled($out,$im,0,0,0,0,imagesx($out),imagesy($out),$w,$h);$ok=$mime==='image/png'?imagepng($out,$dest,6):imagejpeg($out,$dest,85);imagedestroy($out);imagedestroy($im);if(!$ok)throw ValidationException::withMessages(['attachment'=>'The processed image could not be saved.']);}}
