@extends('layouts.admin')
@section('title','Review Property Tax Batch | LandPay')
@section('body_class','admin-page')
@section('content')
@php($activeRows=$batch->rows->where('match_status','!=','inactive'))
@php($inactiveRows=$batch->rows->where('match_status','inactive'))
@php($batchStatus=$batch->status==='not_issued'&&$batch->rows->whereNotNull('existing_invoice_id')->isNotEmpty()?'Not issued — existing invoices detected':str($batch->status)->replace('_',' ')->title())
<section class='admin-section'><div class='container-fluid dashboard-container'>
<div class='admin-heading d-flex flex-wrap justify-content-between gap-3'><div><span class='eyebrow eyebrow-dark'>Property tax {{$batch->tax_year}} · {{$batch->label}}</span><h1>{{$batch->status==='draft'?'Review draft batch':'Batch results'}}</h1><p class='mb-0'>Invoice {{$batch->issue_date->format('M j, Y')}} &middot; due {{$batch->due_date->format('M j, Y')}} &middot; {{$batchStatus}}</p></div><div>@if($batch->status==='draft')<a class='btn btn-outline-brand' href={{route('admin.property-tax-batches.edit',$batch)}}>Edit import</a>@endif <a class='btn btn-outline-brand' href={{route('admin.property-tax-batches.index')}}>All batches</a></div></div>
<div class='row g-3 mt-2'><div class='col-md-3'><div class='admin-next-card'><strong>{{$batch->rows->where('match_status','matched')->count()}}</strong><div>eligible matches</div></div></div><div class='col-md-3'><div class='admin-next-card'><strong>{{\App\Support\Money::format((int)$batch->rows->whereIn('match_status',['matched','draft'])->sum('amount'))}}</strong><div>eligible total</div></div></div><div class='col-md-3'><div class='admin-next-card'><strong>{{$batch->rows->where('match_status','draft')->count()}}</strong><div>draft matches</div></div></div><div class='col-md-3'><div class='admin-next-card'><strong>{{$batch->rows->whereNotIn('match_status',['matched','draft','inactive'])->count()}}</strong><div>exceptions</div></div></div></div>
@if($batch->status==='draft')<div class='alert alert-info mt-4'><strong>No invoices have been created.</strong> Review the rows below, then explicitly create the batch when ready.</div><form method='post' action={{route('admin.property-tax-batches.issue',$batch)}}>@csrf @endif
<div class='admin-next-card mt-4 table-responsive'><table class='table align-middle'><thead><tr><th>Status</th><th>Client</th><th>Plan # / APN</th><th>Description</th><th class='text-end'>Amount</th><th>Email</th>@if($batch->status==='draft'||$batch->rows->where('email_status','failed')->isNotEmpty())<th>Action</th>@endif</tr></thead><tbody>
@foreach($activeRows as $row)
@php($plan=$row->paymentPlan)
@php($membership=$plan?->memberships?->first(fn($m)=>$m->receives_invoices&&$m->role==='primary')??$plan?->memberships?->firstWhere('receives_invoices',true))
@php($client=$membership?->client)
@php($clientName=$client?->organization_name?:trim(($client?->first_name??'').' '.($client?->last_name??'')))
@php($sentAt=$row->email_sent_at??$row->invoice?->emailDeliveries?->where('status','sent')->sortByDesc('sent_at')->first()?->sent_at)
@php($rowLabel=$batch->status==='draft'?str($row->match_status)->title():((in_array($row->match_status,['matched','draft'],true)?'Matched':str($row->match_status)->title()).' — '.match($row->issuance_status){'created'=>'created','excluded'=>'excluded','not_included'=>'not included',default=>'not created'}))
<tr><td>{{$rowLabel}}@if($row->existingInvoice)<small class='d-block'><a href={{route('admin.invoices.show',$row->existingInvoice)}}>Existing invoice: {{$row->existingInvoice->invoice_number}}</a></small>@elseif($row->note)<small class='d-block text-muted'>{{$row->note}}</small>@endif @if($row->duplicate_override)<small class='d-block text-warning'>Duplicate override approved</small>@endif</td><td>{{$clientName?:'-'}}</td><td>{{$plan?->plan_number?:'-'}}<small class='d-block text-muted'>{{$row->original_apn?:'-'}}</small></td><td>{{$row->resolved_description}}</td><td class='money-cell'>{{$row->amount!==null?\App\Support\Money::format($row->amount):'-'}}</td><td>@if($row->invoice_id){{str($row->email_status??'not requested')->replace('_',' ')->title()}}@if($sentAt)<small class='d-block'>Sent {{$sentAt->format('n/j/y g:ia')}}</small>@endif @if($row->email_note)<small class='d-block text-muted'>{{$row->email_note}}</small>@endif @else {{filter_var($client?->email,FILTER_VALIDATE_EMAIL)?$client->email:'Not eligible'}} @endif</td>
@if($batch->status==='draft')<td>@if($row->match_status==='matched'&&$row->existing_invoice_id)<label><input type='checkbox' name='force_duplicates[]' value={{$row->id}}> Create another invoice anyway</label>@elseif($row->match_status==='matched')<label><input type='checkbox' name='exclude_rows[]' value={{$row->id}}> Exclude</label>@elseif($row->match_status==='draft')<label><input type='checkbox' name='include_drafts[]' value={{$row->id}}> Include draft</label>@else Skipped @endif</td>@elseif($batch->rows->where('email_status','failed')->isNotEmpty())<td>@if($row->email_status==='failed')<form method='post' action={{route('admin.property-tax-batches.retry-email',[$batch,$row])}}>@csrf<button class='btn btn-sm btn-outline-brand'>Retry email</button></form>@else - @endif</td>@endif</tr>
@endforeach</tbody></table></div>
@if($batch->status==='draft')<div class='admin-next-card mt-3'><p><strong>Create separate property-tax invoices for every included plan?</strong> Email failures or missing addresses will not prevent invoice creation.</p>@if($batch->rows->whereNotNull('existing_invoice_id')->isNotEmpty())<label class='form-check mb-3'><input class='form-check-input' type='checkbox' name='duplicate_acknowledgment' value='1'> <span class='form-check-label'>I understand that selected override rows already have property-tax invoices for this tax year.</span></label>@endif<button class='btn btn-brand'>Create invoices</button></div></form>@endif
@if($inactiveRows->isNotEmpty())<div class='admin-next-card mt-4'><h2>Skipped inactive plans</h2><p class='text-muted'>Closed, terminated, or deleted plans are shown for review only.</p><div class='table-responsive'><table class='table'><thead><tr><th>Status</th><th>Plan #</th><th>APN</th><th class='text-end'>Amount</th></tr></thead><tbody>@foreach($inactiveRows as $row)<tr><td>{{$row->note}}</td><td>{{$row->paymentPlan?->plan_number}}</td><td>{{$row->original_apn}}</td><td class='money-cell'>{{\App\Support\Money::format((int)$row->amount)}}</td></tr>@endforeach</tbody></table></div></div>@endif
</div></section>
@endsection
