<section class="pb-5 admin-section pt-0"><div class="container-fluid dashboard-container px-2 mt-4"><div class="admin-next-card"><h2>Client portal access</h2><p>The client creates their own password from a single-use invitation link valid for 48 hours.</p>
@if($errors->has('portal_account'))<div class="alert alert-danger">{{$errors->first()}}</div>@endif
@php($latestInvitation=$client->portalInvitations->sortByDesc('created_at')->first())
@if(!$client->portalAccount?->enabled)
@if($latestInvitation?->isUsable())
@if($latestInvitation->encrypted_token)<button id="copy-invitation-link" class="btn btn-outline-brand" type="button" data-link="{{route('portal.invitation.show',$latestInvitation->encrypted_token)}}" hidden>Copy invitation link</button>@endif
@endif
@endif
@if($client->portalAccount?->enabled)<div class="alert alert-success"><strong>Active.</strong> {{$client->portalAccount->email}} <span aria-hidden="true">&mdash;</span> Last login: {{$client->portalAccount->last_login_at?->format('M j, Y g:i A') ?? 'Never'}}</div><div class="d-flex flex-wrap gap-2"><form method="post" action="{{route('admin.portal-access.store',$client)}}">@csrf<button class="btn btn-outline-brand" type="submit">Open client portal as administrator</button></form><form method="post" action="{{route('admin.portal-access.reset',$client)}}" onsubmit="return confirm('Disable current portal access and send a new password setup invitation?');">@csrf<button class="btn btn-brand" type="submit">Reset portal access</button></form><form method="post" action="{{route('admin.portal-access.revoke',$client)}}" onsubmit="return confirm('Revoke portal access? No new invitation will be sent.');">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">Revoke portal access</button></form></div>
@elseif($latestInvitation && $latestInvitation->isUsable())<div class="alert alert-info"><strong>Invitation pending.</strong> Sent to {{$latestInvitation->email}}; expires {{$latestInvitation->expires_at->format('M j, Y g:i A')}}.</div><div class="d-flex gap-2"><form method="post" action="{{route('admin.clients.portal-invitations.store',$client)}}">@csrf<button class="btn btn-brand">Resend invitation</button></form><form method="post" action="{{route('admin.clients.portal-invitations.destroy',[$client,$latestInvitation])}}">@csrf @method('DELETE')<button class="btn btn-outline-danger">Revoke invitation</button></form></div>
@else
@if($client->portalAccount)<div class="alert alert-warning"><strong>Portal access revoked.</strong> Send a new invitation when the client should regain access.</div>@endif<div class="d-flex align-items-center gap-3"><form method="post" action="{{route('admin.clients.portal-invitations.store',$client)}}">@csrf<button class="btn btn-brand">Send portal invitation</button></form>@if($latestInvitation)<small class="text-muted">Previous invitation {{ $latestInvitation->accepted_at ? 'accepted' : ($latestInvitation->revoked_at ? 'revoked' : 'expired') }}.</small>@endif</div>
@endif
</div></div></section>
@push('scripts')<script>{const button=document.getElementById('copy-invitation-link');if(button){const resend=document.querySelector('form[action$="/portal-invitations"]');resend?.parentElement.prepend(button);button.hidden=false;button.addEventListener('click',async()=>{const label=button.textContent;try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(button.dataset.link);else{const area=document.createElement('textarea');area.value=button.dataset.link;document.body.appendChild(area);area.select();document.execCommand('copy');area.remove()}button.textContent='Copied!';setTimeout(()=>button.textContent=label,2000)}catch{window.prompt('Copy this invitation link:',button.dataset.link)}})}}</script>@endpush
