@extends('layouts.admin')
@section('title','Payment methods | LandPay')
@section('body_class','admin-page')
@section('content')
<section class="admin-section"><div class="container-fluid dashboard-container">
<div class="admin-heading d-flex justify-content-between align-items-end"><div><span class="eyebrow eyebrow-dark">Administration</span><h1>Payment methods</h1><p class="mb-0">Choose what clients see and configure each method independently.</p></div><div><a class="btn btn-outline-brand" href="{{route('admin.settings.index')}}">Other settings</a> <a class="btn btn-outline-brand" href="{{route('admin.dashboard')}}">Dashboard</a></div></div>
@if(session('success'))<div class="alert alert-success mt-4">{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger mt-4">{{$errors->first()}}</div>@endif
<ul class="nav nav-tabs settings-tabs mt-4" role="tablist">
<li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#pay-general">General</button></li>
@foreach($methods as $method)<li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#pay-{{$method['key']}}">{{$method['name']}}</button></li>@endforeach
<li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#pay-square">Square</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#pay-stripe">Stripe</button></li>
</ul>
<div class="tab-content">
<div class="tab-pane fade show active" id="pay-general"><div class="admin-next-card mt-4"><h2>Client payment access</h2><form method="post" action="{{route('admin.payment-methods.general.update')}}" class="row g-3">@csrf @method('put')
<div class="col-12 form-check form-switch"><input type="hidden" name="enabled" value="0"><input class="form-check-input" type="checkbox" name="enabled" value="1" id="client-payments" @checked($general['enabled'])><label class="form-check-label" for="client-payments">Enable Make a payment in the client portal</label></div>
<div class="col-12 form-check form-switch"><input type="hidden" name="allow_custom_amount" value="0"><input class="form-check-input" type="checkbox" name="allow_custom_amount" value="1" id="custom-amount" @checked($general['allow_custom_amount'])><label class="form-check-label" for="custom-amount">Allow clients to enter a different amount</label></div>
<div class="col-md-6"><label class="form-label">Card provider</label><select class="form-select" name="card_provider"><option value="disabled">Disabled</option><option value="square" @selected($general['card_provider']==='square')>Square</option><option value="stripe" @selected($general['card_provider']==='stripe')>Stripe</option></select></div>
<div class="col-md-6"><label class="form-label">Payment notice expires after</label><div class="input-group"><input class="form-control" type="number" min="1" max="90" name="intent_expiry_days" value="{{$general['intent_expiry_days']}}"><span class="input-group-text">days</span></div></div><div class="col-12"><button class="btn btn-brand">Save general settings</button></div></form></div></div>
@foreach($methods as $method)<div class="tab-pane fade" id="pay-{{$method['key']}}"><div class="admin-next-card mt-4"><h2>{{$method['name']}}</h2><form method="post" action="{{route('admin.payment-methods.method.update',$method['key'])}}" class="row g-3">@csrf @method('put')
<div class="col-12 form-check form-switch"><input type="hidden" name="enabled" value="0"><input class="form-check-input" type="checkbox" name="enabled" value="1" id="enabled-{{$method['key']}}" @checked($method['enabled'])><label class="form-check-label" for="enabled-{{$method['key']}}">Show this method to clients</label></div>
<div class="col-md-6"><label class="form-label">Display name</label><input class="form-control" name="name" value="{{$method['name']}}" required></div><div class="col-md-6"><label class="form-label">Recipient / handle / address</label><input class="form-control" name="recipient" value="{{$method['recipient']}}"></div>
<div class="col-12"><label class="form-label">Client instructions</label><textarea class="form-control" name="instructions" rows="5">{{$method['instructions']}}</textarea></div><div class="col-md-6"><label class="form-label">Optional link</label><input class="form-control" type="url" name="link" value="{{$method['link']}}"></div><div class="col-md-6"><label class="form-label">Confirmation button</label><input class="form-control" name="button" value="{{$method['button']}}" required></div>
<div class="col-12"><label class="form-label">Optional image or logo URL</label><input class="form-control" type="url" name="image_url" value="{{$method['image_url']}}" placeholder="https://example.com/payment-logo.png"><div class="form-text">Use an HTTPS image. When a payment link is set, clients can click the image to open it.</div></div>
<div class="col-12"><button class="btn btn-brand">Save {{$method['name']}}</button></div></form></div></div>@endforeach
@foreach(['square'=>$square,'stripe'=>$stripe] as $provider=>$values)<div class="tab-pane fade" id="pay-{{$provider}}"><div class="admin-next-card mt-4"><h2>{{ucfirst($provider)}} connection</h2><p class="text-muted">Secrets are encrypted and never displayed after saving. Configure the webhook URL as <code>{{url('/webhooks/'.$provider)}}</code>.</p><form method="post" action="{{route('admin.payment-methods.provider.update',$provider)}}" class="row g-3">@csrf @method('put')
<div class="col-md-4"><label class="form-label">Environment</label><select class="form-select" name="environment"><option value="sandbox">Sandbox / test</option><option value="live" @selected($values['environment']==='live')>Live</option></select></div><div class="col-md-8"><label class="form-label">{{$provider==='square'?'Location ID':'Account / publishable identifier'}}</label><input class="form-control" name="public_id" value="{{$values['public_id']}}"></div>
<div class="col-md-6"><label class="form-label">API secret</label><input class="form-control" type="password" name="api_secret" placeholder="{{$values['api_secret_set']?'Saved - leave blank to keep':'Enter secret'}}"></div><div class="col-md-6"><label class="form-label">Webhook signing secret</label><input class="form-control" type="password" name="webhook_secret" placeholder="{{$values['webhook_secret_set']?'Saved - leave blank to keep':'Enter secret'}}"></div><div class="col-12"><button class="btn btn-brand">Save {{ucfirst($provider)}}</button></div></form></div></div>@endforeach
</div></div></section>
@endsection
