@extends('layouts.admin')
@section('title',($announcement->exists?'Edit':'New').' client announcement | LandPay') @section('body_class','admin-page')
@section('content')
<section class="admin-section"><div class="container-fluid dashboard-container"><div class="admin-heading"><span class="eyebrow eyebrow-dark">Client announcements</span><h1>{{$announcement->exists?'Edit draft':'New announcement'}}</h1><p>Create a concise portal notice. Publishing is a separate confirmation step.</p></div>
@if($errors->any())<div class="alert alert-danger mt-4">{{$errors->first()}}</div>@endif
<form class="admin-next-card h-auto mt-4" method="post" action="{{$announcement->exists?route('admin.announcements.update',$announcement):route('admin.announcements.store')}}">@csrf @if($announcement->exists)@method('PUT')@endif
<div class="row g-3"><div class="col-md-8"><label class="form-label" for="title">Title</label><input class="form-control" id="title" name="title" maxlength="150" required value="{{old('title',$announcement->title)}}"></div><div class="col-md-4"><label class="form-label" for="severity">Type</label><select class="form-select" id="severity" name="severity">@foreach(['information'=>'Information (dismiss)','important'=>'Important (acknowledge)','urgent'=>'Urgent (acknowledge)'] as $v=>$l)<option value="{{$v}}" @selected(old('severity',$announcement->severity?:'information')===$v)>{{$l}}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label" for="body">Announcement</label><x-formatting-editor :value="old('body',$announcement->body)" :rows="7" required /></div>
<div class="col-md-6"><label class="form-label" for="starts_at">Start date and time <span class="text-muted">(optional)</span></label><input class="form-control" type="datetime-local" id="starts_at" name="starts_at" value="{{old('starts_at',$announcement->starts_at?->format('Y-m-d\\TH:i'))}}"><div class="form-text">Blank starts immediately after publishing.</div></div>
<div class="col-md-6"><label class="form-label" for="ends_at">End date and time <span class="text-muted">(optional)</span></label><input class="form-control" type="datetime-local" id="ends_at" name="ends_at" value="{{old('ends_at',$announcement->ends_at?->format('Y-m-d\\TH:i'))}}"><div class="form-text">Blank remains active until deactivated.</div></div>
<div class="col-12"><div class="form-check"><input type="hidden" name="send_email" value="0"><input class="form-check-input" type="checkbox" id="send_email" name="send_email" value="1" @checked(old('send_email',$announcement->exists?$announcement->send_email:true))><label class="form-check-label" for="send_email">Email eligible clients when this announcement starts</label></div><div class="form-text">SMS eligibility is retained for future notification support.</div></div>
<div class="col-12 d-flex gap-2"><button class="btn btn-brand">Save draft</button><a class="btn btn-outline-brand" href="{{route('admin.announcements.index')}}">Cancel</a></div></div></form></div></section>
@endsection
