@extends('layouts.admin')
@section('title',$announcement->title.' | LandPay') @section('body_class','admin-page')
@section('content')
@php($status=$announcement->status()) @php($class=match($status){'active'=>'status-current','scheduled'=>'status-due-soon','draft'=>'status-draft',default=>'status-closed'})
<section class="admin-section"><div class="container-fluid dashboard-container">
<div class="admin-heading d-flex flex-wrap justify-content-between align-items-end gap-3"><div><span class="eyebrow eyebrow-dark">Client announcement</span><div class="d-flex align-items-center gap-2"><h1 class="mb-0">{{$announcement->title}}</h1><span class="dashboard-status {{$class}}">{{str($status)->title()}}</span></div></div><a class="btn btn-outline-brand" href="{{route('admin.announcements.index')}}">Announcements</a></div>
@if(session('publication_success'))
<div class="alert alert-success border-success mt-4" role="alert">
    <div class="fw-bold fs-5">Publication confirmed</div>
    <div>{{session('publication_success')}}</div>
</div>
@endif
@if(session('success'))<div class="alert alert-success mt-4">{{session('success')}}</div>@endif
<article class="admin-next-card h-auto mt-4"><div class="d-flex justify-content-between gap-3"><strong>{{str($announcement->severity)->title()}}</strong><span class="text-muted small">Created {{$announcement->created_at->format('M j, Y g:i A')}}</span></div><div class="mt-3 formatted-text">{!!\App\Support\FormattedText::admin($announcement->body)!!}</div><hr><div class="small text-muted">Starts: {{$announcement->starts_at?->format('M j, Y g:i A')??'When published'}} &middot; Ends: {{$announcement->ends_at?->format('M j, Y g:i A')??'No expiration'}} &middot; Email: {{$announcement->send_email?'Yes':'No'}}</div>
<div class="d-flex flex-wrap gap-2 mt-3">@if(!$announcement->published_at)<a class="btn btn-outline-brand" href="{{route('admin.announcements.edit',$announcement)}}">Edit draft</a><form method="post" action="{{route('admin.announcements.publish',$announcement)}}" onsubmit="return confirm('Publish this announcement to all eligible portal clients?')">@csrf<button class="btn btn-brand">{{$announcement->starts_at?->isFuture()?'Schedule':'Publish'}}</button></form><form method="post" action="{{route('admin.announcements.destroy',$announcement)}}" onsubmit="return confirm('Delete this draft?')">@csrf @method('DELETE')<button class="btn btn-outline-danger">Delete draft</button></form>
@elseif(!$announcement->removed_from_clients_at) @if($announcement->deactivated_at)<form method="post" action="{{route('admin.announcements.reactivate',$announcement)}}">@csrf<button class="btn btn-outline-brand">Reactivate</button></form>@else<form method="post" action="{{route('admin.announcements.deactivate',$announcement)}}">@csrf<button class="btn btn-outline-brand">Deactivate</button></form>@endif<form method="post" action="{{route('admin.announcements.remove',$announcement)}}" onsubmit="return confirm('Remove this announcement from every client banner and history? The admin record will remain.')">@csrf<button class="btn btn-outline-danger">Remove from client history</button></form>@endif</div></article>
@if($announcement->published_at)<div class="admin-next-card h-auto mt-4"><div class="d-flex justify-content-between"><h2>Client activity</h2><span class="small text-muted">{{$announcement->responded_count}} of {{$announcement->recipients_count}} responded</span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Client</th><th>Email</th><th>Notification</th><th>Viewed</th><th>Response</th></tr></thead><tbody>@forelse($recipients as $r)<tr><td>{{$r->client->organization_name?:trim($r->client->first_name.' '.$r->client->last_name)}}</td><td>{{$r->email??'—'}}</td><td><span class="dashboard-status {{$r->email_status==='sent'?'status-current':($r->email_status==='failed'?'status-past-due':'status-draft')}}">{{str($r->email_status)->replace('_',' ')->title()}}</span></td><td>{{$r->first_viewed_at?->format('M j, Y g:i A')??'—'}}</td><td>@if($r->acknowledged_at)Acknowledged {{$r->acknowledged_at->format('M j, Y g:i A')}}@elseif($r->dismissed_at)Dismissed {{$r->dismissed_at->format('M j, Y g:i A')}}@else—@endif</td></tr>@empty<tr><td colspan="5">Recipients will be created when the announcement begins.</td></tr>@endforelse</tbody></table></div>{{$recipients->links()}}</div>@endif
</div></section>@endsection
