<div class='admin-next-card mt-4'><h2>Schedule and retention</h2><form method='post' action='{{route('admin.report-snapshots.update')}}' class='row g-3'>@csrf @method('put')
<div class='col-12'><input type='hidden' name='enabled' value='0'><div class='form-check form-switch'><input class='form-check-input' type='checkbox' id='snapshot-enabled' name='enabled' value='1' @checked(old('enabled',$settings['enabled']))><label class='form-check-label' for='snapshot-enabled'>Enable scheduled report snapshots</label></div></div>
<div class='col-md-4'><label class='form-label'>Frequency</label><select class='form-select' id='snapshot-frequency' name='frequency'>@foreach(['daily'=>'Daily','weekly'=>'Weekly','monthly'=>'Monthly'] as $value=>$label)<option value='{{$value}}' @selected(old('frequency',$settings['frequency'])===$value)>{{$label}}</option>@endforeach</select></div>
<div class='col-md-4'><label class='form-label'>Time</label><input class='form-control' name='time' type='time' value='{{old('time',$settings['time'])}}'></div>
<div class='col-md-4'><label class='form-label'>Day of week</label><select class='form-select' name='weekday'>@foreach(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'] as $value=>$label)<option value='{{$value}}' @selected((int)old('weekday',$settings['weekday'])===$value)>{{$label}}</option>@endforeach</select></div>
<div class='col-md-4'><label class='form-label'>Day of month</label><input class='form-control' name='month_day' type='number' min='1' max='28' value='{{old('month_day',$settings['month_day'])}}'></div>
<div class='col-md-4'><label class='form-label'>Keep latest snapshots</label><input class='form-control' name='keep' type='number' min='1' max='100' value='{{old('keep',$settings['keep'])}}'></div>
<div class='col-12'><div class='form-text mb-3'>Each snapshot contains all six report CSV files outside the public web directory.</div><button class='btn btn-brand'>Save snapshot settings</button></div>
</form></div>
