<?php
namespace App\Http\Controllers\Portal;
use App\Http\Controllers\Controller;use App\Models\AdminNotice;use App\Models\PaymentPlan;use App\Models\SecureMessage;use App\Models\SecureMessageThread;use App\Services\SecureMessageAttachmentService;use App\Services\SecureMessageNotificationService;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Illuminate\View\View;use Throwable;
class SecureMessageController extends Controller{
public function __construct(private readonly SecureMessageAttachmentService $attachments,private readonly SecureMessageNotificationService $notifications){}
public function index(Request $request):View{$threads=SecureMessageThread::query()->where('client_id',$request->user('client')->client_id)->with('paymentPlan')->withCount(['messages as unread_count'=>fn($q)=>$q->where('sender_type','admin')->whereNull('client_viewed_at')])->orderByDesc('latest_message_at')->paginate(20);return view('portal.messages.index',compact('threads'));}
public function create(Request $request):View{return view('portal.messages.create',['plans'=>PaymentPlan::query()->whereHas('memberships',fn($q)=>$q->where('client_id',$request->user('client')->client_id))->orderBy('plan_number')->get()]);}
public function store(Request $request):RedirectResponse{$clientId=$request->user('client')->client_id;$data=$request->validate(['subject'=>['required','string','max:150'],'payment_plan_id'=>['nullable','integer','exists:payment_plans,id'],'body'=>['required','string','max:10000'],'attachment'=>['nullable','file','mimes:jpg,jpeg,png','mimetypes:image/jpeg,image/png','max:10240']]);if(!empty($data['payment_plan_id']))abort_unless(DB::table('payment_plan_clients')->where('client_id',$clientId)->where('payment_plan_id',$data['payment_plan_id'])->exists(),422);$a=$this->attachments->store($request->file('attachment'));try{$thread=DB::transaction(function()use($clientId,$data,$a){$t=SecureMessageThread::query()->create(['client_id'=>$clientId,'payment_plan_id'=>$data['payment_plan_id']??null,'subject'=>$data['subject'],'category'=>'general','latest_message_at'=>now()]);$t->messages()->create($a+['sender_type'=>'client','sender_client_id'=>$clientId,'body'=>$data['body']]);$this->notice($t,'New secure message','sent a new secure message.');return $t;});}catch(Throwable $e){$this->attachments->delete($a);throw $e;}$this->notifications->sendToAdmin($thread);return redirect()->route('portal.messages.show',$thread)->with('success','Your secure message was sent.');}
public function show(Request $request,SecureMessageThread $thread):View{$this->authorizeThread($request,$thread);$thread->messages()->where('sender_type','admin')->whereNull('client_viewed_at')->update(['client_viewed_at'=>now()]);$thread->load(['paymentPlan','messages.senderUser','messages.senderClient']);return view('portal.messages.show',compact('thread'));}
public function reply(Request $request,SecureMessageThread $thread):RedirectResponse{$this->authorizeThread($request,$thread);$data=$request->validate(['body'=>['required','string','max:10000'],'attachment'=>['nullable','file','mimes:jpg,jpeg,png','mimetypes:image/jpeg,image/png','max:10240']]);$a=$this->attachments->store($request->file('attachment'));try{DB::transaction(function()use($request,$thread,$data,$a){$thread->messages()->create($a+['sender_type'=>'client','sender_client_id'=>$request->user('client')->client_id,'body'=>$data['body']]);$thread->update(['latest_message_at'=>now()]);$this->notice($thread,'Secure message reply','replied to "'.$thread->subject.'".');});}catch(Throwable $e){$this->attachments->delete($a);throw $e;}$this->notifications->sendToAdmin($thread);return back()->with('success','Your reply was sent securely.');}
public function download(Request $request,SecureMessageThread $thread,SecureMessage $message){$this->authorizeThread($request,$thread);abort_unless($message->secure_message_thread_id===$thread->id&&filled($message->attachment_path),404);$disk=Storage::disk($message->attachment_disk?:'local');abort_unless($disk->exists($message->attachment_path),404);if($request->boolean('inline')&&in_array($message->attachment_mime,['image/jpeg','image/png'],true))return response()->file($disk->path($message->attachment_path),['Content-Type'=>$message->attachment_mime]);$message->update(['attachment_downloaded_at'=>$message->attachment_downloaded_at??now()]);return $disk->download($message->attachment_path,$message->attachment_name);}
private function notice(SecureMessageThread $thread,string $title,string $action):void{AdminNotice::query()->create(['type'=>'secure_message_reply','client_id'=>$thread->client_id,'secure_message_thread_id'=>$thread->id,'title'=>$title,'message'=>auth('client')->user()->displayName().' '.$action]);}
private function authorizeThread(Request $request,SecureMessageThread $thread):void{abort_unless($thread->client_id===$request->user('client')->client_id,404);}
}
