@extends('layouts.admin')
@section('title','Review monthly invoice | LandPay')
@section('body_class','admin-page')
@section('content')
<section class="admin-section"><div class="container site-container">
<div class="admin-heading d-flex flex-wrap justify-content-between align-items-end gap-3"><div><span class="eyebrow eyebrow-dark">Monthly invoice</span><h1>Review before issuing</h1><p class="mb-0">{{ $plan->title }} <span aria-hidden="true">&middot;</span> APN / Plan # {{ $plan->plan_number }}</p></div><a class="btn btn-outline-brand" href="{{route('admin.plans.show',$plan)}}">Back to plan</a></div>
@if($errors->any())<div class="alert alert-danger mt-4"><strong>Invoice not ready.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
@if($plan->status === 'paused')<div class="alert alert-warning mt-4"><strong>This plan is paused.</strong> This is an explicit manual invoice and is not part of the suspended automatic schedule.</div>@endif
<div class="row g-4 mt-2"><div class="col-lg-7"><form class="admin-next-card" method="post" action="{{route('admin.plans.invoices.preview',$plan)}}">@csrf
<h2>Billing period</h2><p>Review dates, charges, and any fee waiver. Nothing is posted until you issue the invoice.</p>
<p class="alert alert-light border mb-3"><strong>Plan Payment:</strong> {{ \App\Support\Money::format((int)$plan->customary_monthly_payment) }}</p>
<div class="row g-3"><div class="col-md-3"><label class="form-label" for="billing_month">Billing month</label><input class="form-control" type="month" id="billing_month" name="billing_month" required value="{{old('billing_month',$input['billing_month'] ?? $suggestedMonth)}}"></div><div class="col-md-3"><label class="form-label">Plan service fee</label><div class="form-control bg-light">{{\App\Support\Money::format((int)$plan->monthly_service_fee)}}</div></div><div class="col-md-3"><label class="form-label" for="monthly_fee_waiver">Service-fee waiver</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control" id="monthly_fee_waiver" name="monthly_fee_waiver" value="{{old('monthly_fee_waiver',$input['monthly_fee_waiver'] ?? '0.00')}}"></div></div><div class="col-md-3"><label class="form-label" for="waiver_reason">Waiver reason</label><input class="form-control" id="waiver_reason" name="waiver_reason" maxlength="500" value="{{old('waiver_reason',$input['waiver_reason'] ?? '')}}"></div></div>
<div class="d-flex flex-wrap gap-2 mt-4"><button class="btn btn-outline-brand" type="submit">{{ $preview ? 'Refresh preview' : 'Preview invoice' }}</button>@if($preview && !$preview['existing'])<button class="btn btn-brand" type="submit" formaction="{{route('admin.plans.invoices.store',$plan)}}">Issue invoice</button>@endif @if($preview && $preview['existing'])<a class="btn btn-brand" href="{{route('admin.invoices.show',$preview['existing'])}}">View existing invoice</a>@endif</div>
</form></div>
<div class="col-lg-5"><div class="admin-next-card"><h2>Invoice preview</h2>@if(!$preview)<p>Select a billing month to calculate the invoice.</p>@else
<dl class="payment-preview-summary"><div><dt>Invoice</dt><dd>{{$preview['invoice_number']}}</dd></div><div><dt>Issue date</dt><dd>{{$preview['issue_date']->format('M j, Y')}}</dd></div><div><dt>Due date</dt><dd>{{$preview['due_date']->format('M j, Y')}}</dd></div><div><dt>Scheduled payment</dt><dd>{{\App\Support\Money::format($preview['scheduled_amount'])}}</dd></div>@if($preview['monthly_fee_standard']>0)<div><dt>Monthly service fee</dt><dd>{{\App\Support\Money::format($preview['monthly_fee_standard'])}}</dd></div>@endif @if($preview['monthly_fee_waiver']>0)<div><dt>Fee waived</dt><dd>&minus; {{\App\Support\Money::format($preview['monthly_fee_waiver'])}}</dd></div>@endif<div><dt>Total due</dt><dd>{{\App\Support\Money::format($preview['total'])}}</dd></div></dl>
@if($preview['existing'])<div class="alert alert-info mt-3 mb-0">This billing month has already been issued. Repeated submission will not create a duplicate.</div>@endif
@endif</div><article class="admin-summary-card mt-4"><span>Contract balance</span><strong>{{\App\Support\Money::format($contractBalance)}}</strong></article></div></div>
</div></section>
@endsection
