@extends('layouts.app')
@section('title','New payment plan | LandPay')
@section('body_class','admin-page')
@section('content')
@php
$defaultType = $billingDefaults?->stage_one_fee_type?->value ?? 'fixed';
$defaultStageOneValue = $defaultType === 'percentage' ? ($billingDefaults?->stage_one_percentage_rate ?? '0.0000') : number_format(($billingDefaults?->stage_one_fixed_amount ?? 0) / 100, 2, '.', '');
$defaultStageTwoType = $billingDefaults?->stage_two_fee_type?->value ?? 'fixed';
$defaultStageTwoValue = $defaultStageTwoType === 'percentage' ? ($billingDefaults?->stage_two_percentage_rate ?? '0.0000') : number_format(($billingDefaults?->stage_two_fixed_amount ?? 0) / 100, 2, '.', '');
$clientOptions = $clients->map(fn ($client) => ['id' => $client->id, 'label' => $client->organization_name ?: trim($client->first_name.' '.$client->last_name), 'email' => $client->email, 'phone' => $client->primary_phone])->values();
$oldCoClientIds = array_map('strval', old('co_client_ids', []));
@endphp
<section class="admin-section"><div class="container site-container">
<div class="admin-heading"><span class="eyebrow eyebrow-dark">Contract setup</span><h1>New payment plan</h1><p>Set up the property, opening balance, first payment, and recurring billing in order.</p></div>
<form class="admin-form-card" method="POST" action="{{ route('admin.plans.store') }}" id="plan-form">@csrf
@if($errors->any())<div class="alert alert-danger"><strong>The plan was not activated.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<div class="plan-form-section"><div class="plan-form-number">1</div><div class="plan-form-body"><h2>Property</h2><p class="text-muted">Identify the property covered by this agreement.</p><div class="row g-3">
<div class="col-md-4"><label class="form-label">APN / Plan #</label><input class="form-control" name="plan_number" value="{{ old('plan_number') }}" required><div class="form-text">The visible identifier for this property payment plan.</div></div>
<div class="col-md-8"><label class="form-label">Property description</label><input class="form-control" name="title" value="{{ old('title') }}" placeholder="Example: 2.5-acre parcel near County Road 12" required></div>
<div class="col-12"><label class="form-label">Additional property details <span class="text-muted">(optional)</span></label><textarea class="form-control" name="asset_description" rows="2">{{ old('asset_description') }}</textarea></div>
</div></div></div>

<div class="plan-form-section"><div class="plan-form-number">2</div><div class="plan-form-body"><h2>Clients</h2><p class="text-muted">Search existing clients by name, email, or phone. Add a new client without leaving this form.</p><div class="row g-4">
<div class="col-lg-6"><label class="form-label" for="primary_client_search">Primary client</label><div class="client-picker" data-picker="primary"><div class="input-group"><input class="form-control client-search" id="primary_client_search" autocomplete="off" placeholder="Start typing a client name, email, or phone"><button class="btn btn-outline-brand quick-client-button" type="button" data-role="primary">+ New client</button></div><input type="hidden" name="primary_client_id" class="primary-client-id" value="{{ old('primary_client_id',request('client')) }}"><div class="client-results list-group"></div><div class="selected-primary mt-2"></div></div></div>
<div class="col-lg-6"><label class="form-label" for="co_client_search">Co-clients <span class="text-muted">(optional)</span></label><div class="client-picker" data-picker="co"><div class="input-group"><input class="form-control client-search" id="co_client_search" autocomplete="off" placeholder="Search and add a co-client"><button class="btn btn-outline-brand quick-client-button" type="button" data-role="co">+ New client</button></div><div class="client-results list-group"></div><div class="selected-co-clients d-flex flex-wrap gap-2 mt-2"></div></div></div>
</div></div></div>

<div class="plan-form-section"><div class="plan-form-number">3</div><div class="plan-form-body"><h2>Opening contract balance</h2><p class="text-muted">The purchase price plus the documentation fee actually charged establishes the initial balance.</p><div class="row g-3">
<div class="col-md-4"><label class="form-label">Purchase price</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control money-calc" id="purchase_price" name="purchase_price" value="{{ old('purchase_price','0.00') }}" inputmode="decimal" required></div></div>
<div class="col-md-4"><label class="form-label">Documentation fee</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control money-calc" id="documentation_fee_standard" name="documentation_fee_standard" value="{{ old('documentation_fee_standard','0.00') }}" inputmode="decimal" required></div></div>
<div class="col-md-4"><label class="form-label">Fee waived</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control money-calc" id="documentation_fee_waived" name="documentation_fee_waived" value="{{ old('documentation_fee_waived','0.00') }}" inputmode="decimal" required></div></div>
<div class="col-md-8"><label class="form-label">Waiver reason <span class="text-muted">(required when a fee is waived)</span></label><input class="form-control" id="documentation_fee_waiver_reason" name="documentation_fee_waiver_reason" value="{{ old('documentation_fee_waiver_reason') }}"></div>
<div class="col-md-4"><div class="calculation-panel"><span>Documentation fee charged</span><strong id="doc_fee_charged">$0.00</strong></div></div>
<div class="col-12"><div class="calculation-panel calculation-panel-total"><span>Initial contract balance</span><strong id="initial_balance">$0.00</strong></div></div>
</div></div></div>

<div class="plan-form-section"><div class="plan-form-number">4</div><div class="plan-form-body"><h2>Plan beginning and first payment</h2><p class="text-muted">Only the contract start date is required. Leave both first-payment fields blank when the administrator will decide or record the first payment later.</p><div class="row g-3">
<div class="col-md-4"><label class="form-label">Contract start date</label><input type="date" class="form-control" id="contract_start_date" name="contract_start_date" value="{{ old('contract_start_date') }}" required></div>
<div class="col-md-4"><label class="form-label">First payment amount <span class="text-muted">(optional)</span></label><div class="input-group"><span class="input-group-text">$</span><input class="form-control" name="first_payment_amount" value="{{ old('first_payment_amount') }}" inputmode="decimal"></div></div>
<div class="col-md-4"><label class="form-label">First payment due date <span class="text-muted">(optional)</span></label><input type="date" class="form-control" id="first_payment_due_date" name="first_payment_due_date" value="{{ old('first_payment_due_date') }}"><div class="form-text" id="first-payment-interval"></div></div>
<div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="create_first_payment_invoice" value="1" id="create_first_payment_invoice" @checked(old('create_first_payment_invoice'))><label class="form-check-label" for="create_first_payment_invoice"><strong>Create an invoice for the first payment</strong><span class="d-block text-muted">Creates the invoice only. No email is sent to the client.</span></label></div></div>
</div></div></div>

<div class="plan-form-section"><div class="plan-form-number">5</div><div class="plan-form-body"><h2>Recurring monthly invoices</h2><p class="text-muted">These invoices begin on the first configured invoice day after the first-payment due date, or after the contract start date when no first payment is specified.</p><div class="row g-3">
<div class="col-md-4"><label class="form-label">Monthly payment</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control monthly-calc" name="scheduled_payment_amount" id="scheduled_payment_amount" value="{{ old('scheduled_payment_amount', number_format(($billingDefaults?->scheduled_payment_amount ?? 0)/100,2,'.','')) }}" inputmode="decimal" required></div></div>
<div class="col-md-4"><label class="form-label">Monthly service fee</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control monthly-calc" name="monthly_service_fee" id="monthly_service_fee" value="{{ old('monthly_service_fee', number_format(($billingDefaults?->monthly_service_fee ?? 0)/100,2,'.','')) }}" inputmode="decimal" required></div></div>
<div class="col-md-4"><div class="calculation-panel"><span>Expected monthly invoice</span><strong id="monthly_invoice_total">$0.00</strong></div></div>
<div class="col-md-4"><label class="form-label">Invoice day of month</label><input type="number" class="form-control" name="invoice_day" id="invoice_day" min="1" max="31" value="{{ old('invoice_day',$billingDefaults?->invoice_day ?? 3) }}" required></div>
<div class="col-md-4"><label class="form-label">Payment due after</label><div class="input-group"><input type="number" class="form-control" name="due_days_after_issue" id="due_days_after_issue" min="0" max="60" value="{{ old('due_days_after_issue',$billingDefaults?->due_days_after_issue ?? 5) }}" required><span class="input-group-text">days</span></div></div>
<div class="col-md-4"><label class="form-label">Grace period</label><div class="input-group"><input type="number" class="form-control" name="grace_days" id="grace_days" min="0" max="60" value="{{ old('grace_days',$billingDefaults?->grace_days ?? 0) }}" required><span class="input-group-text">days</span></div></div>
<div class="col-12"><div class="schedule-preview" id="schedule-preview"></div></div>
</div></div></div>

<div class="plan-form-section"><div class="plan-form-number">6</div><div class="plan-form-body"><h2>Late fees</h2><p class="text-muted">Stage one occurs automatically on the first day after the grace period. Stage two is optional and must occur later.</p>
<h3>Stage-one late fee</h3><div class="row g-3">
<div class="col-md-4"><label class="form-label">Calculation</label><select class="form-select fee-type" id="stage_one_fee_type" name="stage_one_fee_type"><option value="fixed" @selected(old('stage_one_fee_type',$defaultType)==='fixed')>Fixed dollar amount</option><option value="percentage" @selected(old('stage_one_fee_type',$defaultType)==='percentage')>Percentage of unpaid scheduled payment</option></select></div>
<div class="col-md-4"><label class="form-label fee-value-label" for="stage_one_fee_value">Fee amount</label><div class="input-group"><span class="input-group-text fee-prefix">$</span><input class="form-control" id="stage_one_fee_value" name="stage_one_fee_value" value="{{ old('stage_one_fee_value',$defaultStageOneValue) }}" inputmode="decimal" required><span class="input-group-text fee-suffix d-none">%</span></div></div>
<div class="col-md-4 percentage-minimum"><label class="form-label">Minimum fee amount</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control minimum-input" name="stage_one_minimum_amount" value="{{ old('stage_one_minimum_amount',number_format(($billingDefaults?->stage_one_minimum_amount ?? 0)/100,2,'.','')) }}" inputmode="decimal"></div></div>
<div class="col-12"><div class="schedule-preview">Stage one will be assessed <strong id="stage-one-description"></strong>.</div></div>
</div>
<hr class="my-4"><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="stage_two_enabled" value="1" id="stage_two_enabled" @checked(old('stage_two_enabled',$billingDefaults?->stage_two_enabled ?? false))><label class="form-check-label" for="stage_two_enabled"><strong>Enable a stage-two late fee</strong></label></div>
<div id="stage-two-fields"><h3>Stage-two late fee</h3><div class="row g-3"><div class="col-md-4"><label class="form-label">Assess when invoice is</label><div class="input-group"><input type="number" class="form-control" name="stage_two_days_late" value="{{ old('stage_two_days_late',$billingDefaults?->stage_two_days_late ?? 30) }}" min="1" max="365"><span class="input-group-text">days late</span></div></div>
<div class="col-md-4"><label class="form-label">Calculation</label><select class="form-select fee-type" name="stage_two_fee_type"><option value="fixed" @selected(old('stage_two_fee_type',$defaultStageTwoType)==='fixed')>Fixed dollar amount</option><option value="percentage" @selected(old('stage_two_fee_type',$defaultStageTwoType)==='percentage')>Percentage of unpaid scheduled payment</option></select></div>
<div class="col-md-4"><label class="form-label fee-value-label">Fee amount</label><div class="input-group"><span class="input-group-text fee-prefix">$</span><input class="form-control" name="stage_two_fee_value" value="{{ old('stage_two_fee_value',$defaultStageTwoValue) }}" inputmode="decimal"><span class="input-group-text fee-suffix d-none">%</span></div></div>
<div class="col-md-4 percentage-minimum"><label class="form-label">Minimum fee amount</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control minimum-input" name="stage_two_minimum_amount" value="{{ old('stage_two_minimum_amount',number_format(($billingDefaults?->stage_two_minimum_amount ?? 0)/100,2,'.','')) }}" inputmode="decimal"></div></div></div></div>
</div></div>

<div class="plan-form-section plan-form-section-advanced"><div class="plan-form-number">7</div><div class="plan-form-body"><h2>Advanced account rule</h2><p class="text-muted">Normally leave this company-default value unchanged.</p><div class="row"><div class="col-md-5"><label class="form-label">Default eligibility after</label><div class="input-group"><input class="form-control" type="number" name="default_eligibility_days" min="1" max="730" value="{{ old('default_eligibility_days',$billingDefaults?->default_eligibility_days ?? 60) }}" required><span class="input-group-text">days</span></div></div></div></div></div>

<div class="form-check mt-4"><input class="form-check-input" type="checkbox" name="contact_risk_acknowledged" value="1" id="risk" @checked(old('contact_risk_acknowledged')) required><label class="form-check-label" for="risk">The selected clients and contract contact details have been reviewed.</label></div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-brand btn-lg">Review and activate payment plan</button><a class="btn btn-outline-brand btn-lg" href="{{ route('admin.plans.index') }}">Cancel</a></div>
</form></div></section>

<div class="modal fade" id="quickClientModal" tabindex="-1" aria-labelledby="quickClientTitle" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-4" id="quickClientTitle">Add a new client</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-danger d-none" id="quick-client-errors"></div><div class="row g-3"><div class="col-12"><label class="form-label">Client type</label><select class="form-select" id="quick_client_type"><option value="individual">Individual</option><option value="organization">Organization</option></select></div><div class="col-12"><label class="form-label">Organization name</label><input class="form-control" id="quick_organization_name"></div><div class="col-6"><label class="form-label">First name</label><input class="form-control" id="quick_first_name"></div><div class="col-6"><label class="form-label">Last name</label><input class="form-control" id="quick_last_name"></div><div class="col-6"><label class="form-label">Email</label><input class="form-control" type="email" id="quick_email"></div><div class="col-6"><label class="form-label">Phone</label><input class="form-control" id="quick_phone"></div></div></div><div class="modal-footer"><button class="btn btn-outline-brand" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-brand" type="button" id="save-quick-client">Add client</button></div></div></div></div>
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', () => {
 let clients = @json($clientOptions);
 let primaryId = String(document.querySelector('.primary-client-id').value || ''), coIds = new Set(@json($oldCoClientIds)), quickRole = 'primary';
 const money = value => Number(String(value || 0).replace(/[$,]/g,'')) || 0, currency = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
 const clientById = id => clients.find(client => String(client.id) === String(id));
 function renderSelections(){ const primary=clientById(primaryId), primaryBox=document.querySelector('.selected-primary'); primaryBox.innerHTML=primary ? `<span class="selected-client-chip"><strong>${primary.label}</strong><button type="button" aria-label="Remove primary client">&times;</button></span>` : '<span class="text-muted small">No primary client selected.</span>'; document.querySelector('.primary-client-id').value=primaryId; primaryBox.querySelector('button')?.addEventListener('click',()=>{primaryId='';renderSelections();}); const coBox=document.querySelector('.selected-co-clients'); coBox.innerHTML=''; coIds.forEach(id=>{if(id===primaryId){coIds.delete(id);return;} const client=clientById(id); if(!client)return; const chip=document.createElement('span'); chip.className='selected-client-chip'; chip.innerHTML=`<strong>${client.label}</strong><button type="button" aria-label="Remove ${client.label}">&times;</button><input type="hidden" name="co_client_ids[]" value="${client.id}">`; chip.querySelector('button').addEventListener('click',()=>{coIds.delete(String(client.id));renderSelections();});coBox.appendChild(chip);}); if(!coBox.children.length)coBox.innerHTML='<span class="text-muted small">No co-clients selected.</span>'; }
 function bindPicker(picker){ const input=picker.querySelector('.client-search'),results=picker.querySelector('.client-results'),role=picker.dataset.picker; const show=()=>{const query=input.value.trim().toLowerCase();results.innerHTML='';if(!query){results.classList.remove('show');return;} clients.filter(c=>`${c.label} ${c.email||''} ${c.phone||''}`.toLowerCase().includes(query)).filter(c=>role==='primary'||String(c.id)!==primaryId).slice(0,6).forEach(client=>{const button=document.createElement('button');button.type='button';button.className='list-group-item list-group-item-action';button.innerHTML=`<strong>${client.label}</strong><small>${[client.email,client.phone].filter(Boolean).join(' &middot; ')}</small>`;button.addEventListener('click',()=>{if(role==='primary'){primaryId=String(client.id);coIds.delete(primaryId);}else coIds.add(String(client.id));input.value='';results.classList.remove('show');renderSelections();});results.appendChild(button);});results.classList.toggle('show',results.children.length>0);}; input.addEventListener('input',show); input.addEventListener('focus',show); }
 document.querySelectorAll('.client-picker').forEach(bindPicker); renderSelections();
 const modal=new bootstrap.Modal(document.getElementById('quickClientModal')); document.querySelectorAll('.quick-client-button').forEach(button=>button.addEventListener('click',()=>{quickRole=button.dataset.role;document.getElementById('quick-client-errors').classList.add('d-none');modal.show();}));
 document.getElementById('save-quick-client').addEventListener('click',async()=>{const payload={client_type:document.getElementById('quick_client_type').value,organization_name:document.getElementById('quick_organization_name').value,first_name:document.getElementById('quick_first_name').value,last_name:document.getElementById('quick_last_name').value,email:document.getElementById('quick_email').value,primary_phone:document.getElementById('quick_phone').value,country_code:'US'};const response=await fetch(@json(route('admin.clients.quick-store')),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':@json(csrf_token())},body:JSON.stringify(payload)});if(!response.ok){const body=await response.json();const errors=Object.values(body.errors||{}).flat();const box=document.getElementById('quick-client-errors');box.textContent=errors.join(' &middot; ');box.classList.remove('d-none');return;}const client=await response.json();clients.push(client);if(quickRole==='primary')primaryId=String(client.id);else coIds.add(String(client.id));modal.hide();renderSelections();});
 function calculate(){const standard=money(document.getElementById('documentation_fee_standard').value),waived=money(document.getElementById('documentation_fee_waived').value),charged=Math.max(0,standard-waived);document.getElementById('doc_fee_charged').textContent=currency(charged);document.getElementById('initial_balance').textContent=currency(money(document.getElementById('purchase_price').value)+charged);document.getElementById('monthly_invoice_total').textContent=currency(money(document.getElementById('scheduled_payment_amount').value)+money(document.getElementById('monthly_service_fee').value));document.getElementById('documentation_fee_waiver_reason').required=waived>0;const grace=Number(document.getElementById('grace_days').value||0),due=Number(document.getElementById('due_days_after_issue').value||0),invoiceDay=document.getElementById('invoice_day').value;document.getElementById('stage-one-description').textContent=`${grace+1} day${grace===0?'':'s'} after the due date`;document.getElementById('schedule-preview').innerHTML=`Invoices issue on day <strong>${invoiceDay}</strong> of each month, are due <strong>${due} days later</strong>, and receive the stage-one fee on the first day after the <strong>${grace}-day grace period</strong>.`;const start=document.getElementById('contract_start_date').value,firstDue=document.getElementById('first_payment_due_date').value;if(start&&firstDue){const days=Math.round((new Date(firstDue+'T00:00:00')-new Date(start+'T00:00:00'))/86400000);document.getElementById('first-payment-interval').textContent=days>=0?`Due ${days} days after the contract starts.`:'';}else document.getElementById('first-payment-interval').textContent='';}
 document.querySelectorAll('.money-calc,.monthly-calc').forEach(input=>input.addEventListener('focus',()=>{if(input.value==='0.00')input.select();}));
 document.querySelectorAll('.money-calc,.monthly-calc,#grace_days,#due_days_after_issue,#invoice_day,#contract_start_date,#first_payment_due_date').forEach(input=>input.addEventListener('input',calculate));
 function syncFee(select){const row=select.closest('.row'),percentage=select.value==='percentage';row.querySelector('.fee-prefix')?.classList.toggle('d-none',percentage);row.querySelector('.fee-suffix')?.classList.toggle('d-none',!percentage);row.querySelector('.fee-value-label').textContent=percentage?'Fee percentage':'Fee amount';row.querySelector('.percentage-minimum')?.classList.toggle('d-none',!percentage);const minimum=row.querySelector('.minimum-input');if(minimum)minimum.required=percentage;}
 document.querySelectorAll('.fee-type').forEach(select=>{select.addEventListener('change',()=>syncFee(select));syncFee(select);});const stageTwo=document.getElementById('stage_two_enabled'),stageTwoFields=document.getElementById('stage-two-fields');const syncStageTwo=()=>{stageTwoFields.classList.toggle('d-none',!stageTwo.checked);stageTwoFields.querySelectorAll('input,select').forEach(input=>input.disabled=!stageTwo.checked);};stageTwo.addEventListener('change',syncStageTwo);syncStageTwo();calculate();
});
</script>
@endpush
