@extends('layouts.app')
@section('title','Make a payment | LandPay')
@section('body_class','admin-page')
@section('content')
<section class="admin-section"><div class="container site-container">
<div class="admin-heading d-flex justify-content-between align-items-end"><div><span class="eyebrow eyebrow-dark">Client portal</span><h1>Make a payment</h1><p class="mb-0">Choose the amount and payment method.</p></div><a class="btn btn-outline-brand" href="{{route('portal.dashboard')}}">Dashboard</a></div>
@if($errors->any())<div class="alert alert-danger mt-4">{{$errors->first()}}</div>@endif
<form class="admin-next-card mt-4" method="post" action="{{route('portal.make-payment.preview')}}">@csrf
<div class="row g-3"><div class="col-md-6"><label class="form-label">Payment plan</label><select class="form-select" name="payment_plan_id">@foreach($plans as $plan)<option value="{{$plan->id}}" @selected((int)$input['payment_plan_id']===$plan->id)>{{$plan->plan_number}} &mdash; {{$plan->title}}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Amount</label><div class="input-group"><span class="input-group-text">$</span><input class="form-control" name="amount" inputmode="decimal" value="{{$input['amount']}}" @readonly(!$general['allow_custom_amount']) required></div></div></div>
<h2 class="mt-4">Choose a payment method</h2><div class="payment-method-carousel" role="radiogroup">@forelse($methods as $method)<label class="payment-method-card {{$method['recommended']?'is-recommended':''}}" data-button="{{$method['button']}}"><input type="radio" name="method" value="{{$method['key']}}" @checked(($input['method']??$methods[0]['key'])===$method['key'])><strong>{{$method['name']}}</strong>@if($method['recommended'])<span class="badge text-bg-success">Recommended</span>@endif</label>@empty<p>No payment methods are currently available. Please contact us.</p>@endforelse</div>
@foreach($methods as $method)<div class="payment-method-details mt-3" data-method-details="{{$method['key']}}"><h3 class="h5">{{$method['name']}}</h3>@if($method['recipient'])<p><strong>{{$method['recipient']}}</strong></p>@endif<p>{!! nl2br(e($method['instructions'])) !!}</p>@if($method['link'])<p><a href="{{$method['link']}}" target="_blank" rel="noopener">Open {{$method['name']}}</a></p>@endif</div>@endforeach
@if($preview)<hr><h2>Allocation preview</h2><ul>@foreach($preview['allocations'] as $allocation)<li>{{$allocation['label']}}: {{\App\Support\Money::format($allocation['amount'])}}</li>@endforeach</ul>@if($preview['overpayment_amount']>0)<fieldset><legend class="h5">How should the extra {{\App\Support\Money::format($preview['overpayment_amount'])}} be used?</legend><label><input type="radio" name="overpayment_disposition" value="principal"> Apply to principal</label><br><label><input type="radio" name="overpayment_disposition" value="next_invoice_credit"> Carry forward as credit</label></fieldset>@endif
<div class="row g-3 mt-2"><div class="col-md-6"><label class="form-label">Reference or confirmation number</label><input class="form-control" name="client_reference" value="{{$input['client_reference']??''}}"></div><div class="col-md-6"><label class="form-label">Note (optional)</label><input class="form-control" name="client_note" value="{{$input['client_note']??''}}"></div></div>
<button class="btn btn-brand mt-4" id="payment-confirm-button" formaction="{{route('portal.make-payment.store')}}">Notify us about this payment</button>
@endif<button class="btn btn-outline-brand mt-4">Preview payment</button></form></div></section>
@push('scripts')<script>const sync=()=>{const selected=document.querySelector('input[name=method]:checked');const value=selected?.value;document.querySelectorAll('[data-method-details]').forEach(el=>el.hidden=el.dataset.methodDetails!==value);const button=document.getElementById('payment-confirm-button');if(button&&selected?.closest('[data-button]'))button.textContent=selected.closest('[data-button]').dataset.button};document.querySelectorAll('input[name=method]').forEach(el=>el.addEventListener('change',sync));sync();</script>@endpush
@endsection