@extends('layouts.admin')
@section('title','Documents | LandPay')
@section('body_class','admin-page')
@section('content')
<section class="admin-section"><div class="container-fluid dashboard-container">
<div class="admin-heading d-flex flex-wrap justify-content-between align-items-end gap-3"><div><span class="eyebrow eyebrow-dark">Administration</span><h1>Documents</h1><p class="mb-0">Private files shared between LandPay and clients.</p></div><button class="btn btn-sun" type="button" data-bs-toggle="collapse" data-bs-target="#document-upload" aria-expanded="{{$errors->any()?'true':'false'}}" aria-controls="document-upload">Upload document</button></div>
@if(session('success'))<div class="alert alert-success mt-4">{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger mt-4">{{$errors->first()}}</div>@endif
<div class="collapse {{$errors->any()?'show':''}}" id="document-upload"><div class="admin-next-card h-auto mt-4"><div class="d-flex justify-content-between align-items-center gap-3"><div><h2 class="mb-1">Upload document</h2><p class="mb-0 text-muted">Choose a client and add one private file.</p></div><button class="btn-close" type="button" data-bs-toggle="collapse" data-bs-target="#document-upload" aria-label="Close upload form"></button></div>
<form method="post" action="{{route('admin.documents.store')}}" enctype="multipart/form-data">@csrf
<div class="row g-3 mt-1">
<div class="col-lg-7"><label class="form-label" for="client_search">Client</label><input class="form-control" id="client_search" list="client_options" autocomplete="off" placeholder="Start typing a name, organization, or email" required><input type="hidden" id="client_id" name="client_id" value="{{old('client_id')}}"><datalist id="client_options">@foreach($clients as $client)@php($clientLabel=($client->organization_name ?: trim($client->first_name.' '.$client->last_name)).($client->email?' - '.$client->email:''))<option value="{{$clientLabel}}" data-id="{{$client->id}}" @if(old('client_id')==$client->id) data-selected="true" @endif></option>@endforeach</datalist></div>
<div class="col-lg-5"><label class="form-label" for="payment_plan_id">Payment plan</label><select class="form-select" id="payment_plan_id" name="payment_plan_id" disabled><option value="">Select a client first</option>@foreach($plans as $plan)<option value="{{$plan->id}}" data-client-ids="{{$plan->memberships->pluck('client_id')->join(',')}}" @selected(old('payment_plan_id')==$plan->id)>{{$plan->plan_number}} &mdash; {{$plan->title}}</option>@endforeach</select></div>
<div class="col-12"><label class="document-drop-zone" id="document_drop_zone" for="document" tabindex="0"><input id="document" name="document" type="file" accept=".pdf,.jpg,.jpeg,.png,.docx" required hidden><strong id="document_file_name">Drop a file here, paste an image, or click to browse</strong><span id="document_file_help">PDF, DOCX, JPG, or PNG � 10 MB maximum</span></label></div>
<div class="col-md-5"><label class="form-label" for="category">Category</label><select class="form-select" id="category" name="category">@foreach(['general'=>'General','contract'=>'Contract','closing_document'=>'Closing document','identification'=>'Identification','property_image'=>'Property image'] as $value=>$label)<option value="{{$value}}" @selected(old('category','general')===$value)>{{$label}}</option>@endforeach</select></div>
<div class="col-md-7 d-flex flex-wrap align-items-end gap-4 pb-2"><div class="form-check"><input type="hidden" name="visible_to_client" value="0"><input class="form-check-input" type="checkbox" name="visible_to_client" value="1" id="visible_to_client" @checked(old('visible_to_client','1'))><label class="form-check-label" for="visible_to_client">Share with client</label></div><div class="form-check"><input type="hidden" name="notify_client" value="0"><input class="form-check-input" type="checkbox" name="notify_client" value="1" id="notify_client" @checked(old('notify_client'))><label class="form-check-label" for="notify_client">Notify with secure message</label></div></div>
<div class="col-12" id="notification_message" @if(!old('notify_client')) hidden @endif><label class="form-label" for="message">Notification message</label><textarea class="form-control" id="message" name="message" rows="2" maxlength="10000" placeholder="A new document has been shared with you.">{{old('message')}}</textarea></div>
</div><div class="d-flex justify-content-end gap-2 mt-3"><button class="btn btn-outline-brand" type="button" data-bs-toggle="collapse" data-bs-target="#document-upload">Cancel</button><button class="btn btn-brand">Upload document</button></div></form></div></div>
@php($filteredClient=$clients->firstWhere('id',(int)request('client')))
@php($filteredClientLabel=$filteredClient ? (($filteredClient->organization_name ?: trim($filteredClient->first_name.' '.$filteredClient->last_name)).($filteredClient->email?' - '.$filteredClient->email:'')) : '')
<form class="d-flex flex-wrap gap-2 mt-4 mb-3" method="get" id="document_filters"><input class="form-control" style="max-width:28rem" id="filter_client_search" list="client_options" autocomplete="off" placeholder="All clients - start typing to filter" value="{{$filteredClientLabel}}"><input type="hidden" id="filter_client_id" name="client" value="{{request('client')}}"><label class="form-check align-self-center"><input class="form-check-input" type="checkbox" name="archived" value="1" @checked(request()->boolean('archived'))> Include archived</label><button class="btn btn-outline-brand">Filter</button></form>
<script>(()=>{const search=document.getElementById('filter_client_search'),client=document.getElementById('filter_client_id'),options=[...document.querySelectorAll('#client_options option')],labels=new Map(options.map(option=>[option.value,option.dataset.id]));function sync(){client.value=labels.get(search.value)||''}search.addEventListener('input',sync);document.getElementById('document_filters').addEventListener('submit',sync)})()</script>
<div class="dashboard-table-card"><div class="table-responsive"><table class="table dashboard-table align-middle mb-0"><thead><tr><th class="dashboard-actions-menu">Actions</th><th>Client</th><th>Document</th><th>Plan</th><th>Category</th><th>Shared</th><th>Uploaded</th></tr></thead><tbody>
@forelse($documents as $document)
<tr>
<td class="dashboard-actions-menu"><div class="dropdown"><button class="btn btn-sm btn-light dashboard-menu-button" type="button" data-bs-toggle="dropdown" data-bs-boundary="viewport" aria-expanded="false" aria-label="Actions for {{$document->name}}"><span aria-hidden="true">&#8942;</span></button><ul class="dropdown-menu dropdown-menu-end">@if(in_array($document->mime,['application/pdf','image/jpeg','image/png'],true))<li><button class="dropdown-item" type="button" data-document-preview="{{route('admin.documents.preview',$document)}}" data-document-name="{{$document->name}}">Preview</button></li>@endif<li><a class="dropdown-item" href="{{route('admin.documents.download',$document)}}">Download</a></li><li><form method="post" action="{{route('admin.documents.visibility',$document)}}">@csrf<button class="dropdown-item">{{$document->visible_to_client ? 'Hide from client' : 'Share with client'}}</button></form></li><li><form method="post" action="{{route('admin.documents.archive',$document)}}">@csrf<button class="dropdown-item">{{$document->archived_at ? 'Restore' : 'Archive'}}</button></form></li><li><form method="post" action="{{route('admin.documents.destroy',$document)}}" onsubmit="return confirm('Permanently delete this document? This cannot be undone.')">@csrf @method('DELETE')<button class="dropdown-item text-danger">Delete permanently</button></form></li></ul></div></td>
<td><a class="dashboard-plan-link" href="{{route('admin.clients.show',$document->client)}}">{{$document->client->organization_name ?: trim($document->client->first_name.' '.$document->client->last_name)}}</a></td>
<td>@if(in_array($document->mime,['application/pdf','image/jpeg','image/png'],true))<button class="btn btn-link p-0 align-baseline" type="button" data-document-preview="{{route('admin.documents.preview',$document)}}" data-document-name="{{$document->name}}">{{$document->name}}</button>@else<a href="{{route('admin.documents.download',$document)}}">{{$document->name}}</a>@endif<div class="small text-muted">{{number_format($document->size/1024)}} KB @if($document->archived_at) &middot; Archived @endif</div></td>
<td>@if($document->paymentPlan)<a href="{{route('admin.plans.show',$document->paymentPlan)}}">{{$document->paymentPlan->plan_number}} &mdash; {{$document->paymentPlan->title}}</a>@else &mdash; @endif</td>
<td>{{str($document->category)->replace('_',' ')->title()}}</td>
<td>
    @if($document->visible_to_client)
        <span class="dashboard-status status-current fs-6 status-tight">
            <span aria-hidden="true">&#10003;</span> Yes
        </span>
    @else
        <span class="dashboard-status status-due fs-6">
            <span aria-hidden="true">&times;</span> No
        </span>
    @endif
</td>
<td>{{$document->created_at->format('M j, Y')}}<div class="small text-muted">{{$document->uploadedByClient ? 'Client' : 'Administrator'}}</div></td>
</tr>
@empty
<tr><td colspan="7" class="dashboard-empty">No documents found.</td></tr>
@endforelse
</tbody></table></div></div><div class="dashboard-pagination">{{$documents->links()}}</div>
</div></section>
<div class="modal fade" id="documentPreviewModal" tabindex="-1" aria-labelledby="documentPreviewTitle" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5 text-start" id="documentPreviewTitle">Document preview</h2><button class="btn-close ms-auto" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body p-0"><iframe id="documentPreviewFrame" title="Document preview" style="width:100%;height:75vh;border:0"></iframe></div><div class="modal-footer justify-content-end"><a class="btn btn-outline-brand" id="documentPreviewDownload" href="#">Download</a></div></div></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const element=document.getElementById('documentPreviewModal'),frame=document.getElementById('documentPreviewFrame'),title=document.getElementById('documentPreviewTitle'),download=document.getElementById('documentPreviewDownload'),modal=new bootstrap.Modal(element);document.querySelectorAll('[data-document-preview]').forEach(button=>button.addEventListener('click',()=>{title.textContent=button.dataset.documentName;frame.src=button.dataset.documentPreview;download.href=button.dataset.documentPreview.replace(/\/preview$/,'');modal.show()}));element.addEventListener('hidden.bs.modal',()=>frame.src='about:blank')})</script>
@endsection
@push('styles')<style>.document-drop-zone{min-height:120px;border:2px dashed #b9c5c5;border-radius:.5rem;background:#f8faf9;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:1.5rem;cursor:pointer;transition:.15s ease}.document-drop-zone:hover,.document-drop-zone:focus,.document-drop-zone.is-dragging{border-color:#173f40;background:#f0f6f5;outline:none}.document-drop-zone span{color:#6c757d;font-size:.9rem;margin-top:.3rem}</style>@endpush
@push('scripts')<script>(()=>{const search=document.getElementById('client_search'),client=document.getElementById('client_id'),options=[...document.querySelectorAll('#client_options option')],plan=document.getElementById('payment_plan_id'),file=document.getElementById('document'),zone=document.getElementById('document_drop_zone'),fileName=document.getElementById('document_file_name'),fileHelp=document.getElementById('document_file_help'),notify=document.getElementById('notify_client'),message=document.getElementById('notification_message');const labels=new Map(options.map(option=>[option.value,option.dataset.id]));function syncClient(){client.value=labels.get(search.value)||'';const matches=[...plan.options].filter((option,index)=>{if(index===0)return false;const match=option.dataset.clientIds.split(',').includes(client.value);option.hidden=!match;return match});plan.disabled=!client.value;plan.options[0].textContent=client.value?(matches.length?'No specific plan':'No associated plans'):'Select a client first';if(matches.length===1)plan.value=matches[0].value;else if(!matches.some(option=>option.value===plan.value))plan.value=''}function showFile(){const selected=file.files[0];fileName.textContent=selected?selected.name:'Drop a file here, paste an image, or click to browse';fileHelp.textContent=selected?Math.max(1,Math.round(selected.size/1024))+' KB':'PDF, DOCX, JPG, or PNG • 10 MB maximum'}function setFiles(files){if(!files?.length)return;const transfer=new DataTransfer();transfer.items.add(files[0]);file.files=transfer.files;showFile()}search.addEventListener('input',syncClient);zone.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();file.click()}});file.addEventListener('change',showFile);zone.addEventListener('dragover',event=>{event.preventDefault();zone.classList.add('is-dragging')});zone.addEventListener('dragleave',()=>zone.classList.remove('is-dragging'));zone.addEventListener('drop',event=>{event.preventDefault();zone.classList.remove('is-dragging');setFiles(event.dataTransfer.files)});zone.addEventListener('paste',event=>setFiles(event.clipboardData.files));notify.addEventListener('change',()=>message.hidden=!notify.checked);const selected=options.find(option=>option.dataset.selected);if(selected)search.value=selected.value;syncClient();showFile()})()</script>@endpush
