@extends('layouts.admin')
@section('title','New secure message | LandPay')
@section('body_class','admin-page')
@section('content')
<section class="admin-section"><div class="container-fluid dashboard-container"><div class="admin-heading"><span class="eyebrow eyebrow-dark">Secure messages</span><h1>New secure message</h1><p>Send private instructions with one optional attachment.</p></div>
@if($errors->any())<div class="alert alert-danger mt-4">{{$errors->first()}}</div>@endif
<form class="admin-next-card h-auto mt-4" method="post" action="{{route('admin.messages.store')}}" enctype="multipart/form-data">@csrf<div class="row g-3">
<div class="col-md-6"><label class="form-label" for="client_search">Client</label><input class="form-control" id="client_search" list="client_options" autocomplete="off" placeholder="Start typing a name, organization, or email" required><input type="hidden" id="client_id" name="client_id" value="{{old('client_id',$selectedClientId)}}"><datalist id="client_options">@foreach($clients as $client)@php($clientLabel=($client->organization_name ?: trim($client->first_name.' '.$client->last_name)).($client->email?' - '.$client->email:''))<option value="{{$clientLabel}}" data-id="{{$client->id}}" @if((int)old('client_id',$selectedClientId)===$client->id) data-selected="true" @endif></option>@endforeach</datalist></div>
<div class="col-md-6"><label class="form-label" for="payment_plan_id">Plan reference (optional)</label><select class="form-select" id="payment_plan_id" name="payment_plan_id"><option value="">No plan reference</option>@foreach($plans as $plan)<option value="{{$plan->id}}" data-client-ids="{{$plan->memberships->pluck('client_id')->join(',')}}" @selected((int)old('payment_plan_id',$selectedPlanId)===$plan->id)>{{$plan->plan_number}} &mdash; {{$plan->title}}</option>@endforeach</select></div>
<div class="col-md-8"><label class="form-label" for="subject">Subject</label><input class="form-control" id="subject" name="subject" maxlength="150" value="{{old('subject')}}" required></div>
<div class="col-md-4"><label class="form-label" for="category">Category</label><select class="form-select" id="category" name="category">@foreach(['general'=>'General','closing_documents'=>'Closing documents','contract'=>'Contract'] as $value=>$label)<option value="{{$value}}" @selected(old('category','general')===$value)>{{$label}}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label" for="body">Message</label><textarea class="form-control" id="body" name="body" rows="8" maxlength="10000" required>{{old('body')}}</textarea></div>
<div class="col-12">@include('shared.message-file-picker',['pickerId'=>'new-message-files','clientSearchId'=>'client_search'])</div>
<div class="col-12 d-flex gap-2"><button class="btn btn-brand" type="submit">Send secure message</button><a class="btn btn-outline-brand" href="{{route('admin.messages.index')}}">Cancel</a></div></div></form></div></section>
@push('scripts')<script>(()=>{const search=document.getElementById('client_search'),client=document.getElementById('client_id'),options=[...document.querySelectorAll('#client_options option')],labels=new Map(options.map(option=>[option.value,option.dataset.id])),plan=document.getElementById('payment_plan_id');function filter(){client.value=labels.get(search.value)||'';const plans=[...plan.options].filter((option,index)=>{if(index===0)return false;const match=option.dataset.clientIds.split(',').includes(client.value);option.hidden=!match;return match});plan.options[0].textContent=client.value?(plans.length?'No plan reference':'No associated plans'):'Select a client first';plan.disabled=!client.value;if(plans.length===1)plan.value=plans[0].value;else if(!plans.some(option=>option.value===plan.value))plan.value=''}search.addEventListener('input',filter);const selected=options.find(option=>option.dataset.selected);if(selected)search.value=selected.value;filter()})()</script>@endpush
@endsection
