@extends('layouts.admin')
@section('title',$thread->subject.' | LandPay')
@section('body_class','admin-page')
@section('content')
<section class="admin-section"><div class="container-fluid dashboard-container">
<div class="admin-heading d-flex flex-wrap justify-content-between align-items-end gap-3"><div><span class="eyebrow eyebrow-dark">{{str($thread->category)->replace('_',' ')->title()}}</span><h1>{{$thread->subject}}</h1><p class="mb-0">{{$thread->client->organization_name ?: trim($thread->client->first_name.' '.$thread->client->last_name)}} @if($thread->paymentPlan)&middot; <a href="{{route('admin.plans.show',$thread->paymentPlan)}}">Plan {{$thread->paymentPlan->plan_number}}</a>@endif</p></div><div class="d-flex gap-2"><form method="post" action="{{route('admin.messages.star',$thread)}}">@csrf<button class="btn btn-outline-brand">{{$thread->starred_at?'★ Starred':'☆ Follow up'}}</button></form><a class="btn btn-outline-brand" href="{{route('admin.messages.index')}}">Messages</a><div class="dropdown"><button class="btn btn-outline-brand" type="button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Conversation actions">&#8942;</button><ul class="dropdown-menu dropdown-menu-end"><li><form method="post" action="{{route('admin.messages.destroy',$thread)}}" onsubmit="return confirm('Permanently delete this conversation with {{$thread->client->organization_name ?: trim($thread->client->first_name.' '.$thread->client->last_name)}}: {{$thread->subject}} and all attachments?')">@csrf @method('DELETE')<button class="dropdown-item text-danger" type="submit">Delete conversation</button></form></li></ul></div></div></div>
@if(session('success'))<div class="alert alert-success mt-4">{{session('success')}}</div>@endif
@if(session('error'))<div class="alert alert-danger mt-4">{{session('error')}}</div>@endif
@if($errors->any())<div class="alert alert-danger mt-4">{{$errors->first()}}</div>@endif
<div class="admin-next-card h-auto mt-4">
@foreach($thread->messages as $message)<article class="border-bottom pb-3 mb-3"><div class="d-flex justify-content-between gap-3"><strong>{{$message->sender_type==='admin'?($message->senderUser?->name ?? 'Administrator'):($message->senderClient?->organization_name ?: trim(($message->senderClient?->first_name ?? '').' '.($message->senderClient?->last_name ?? '')))}}</strong><span class="text-muted">{{$message->created_at->format('M j, Y g:i A')}}</span></div><div style="white-space:pre-wrap">{{$message->body}}</div>
@if($message->attachment_path)<div class="d-flex align-items-center gap-2 mt-3 mb-1"><a class="btn btn-sm btn-outline-brand" href="{{route('admin.messages.download',[$thread,$message])}}">Download {{$message->attachment_name}}</a><div class="dropdown"><button class="btn btn-sm btn-light dashboard-menu-button" type="button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Attachment actions">&#8942;</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="{{route('admin.messages.download',[$thread,$message])}}">Download</a></li><li><form method="post" action="{{route('admin.messages.attachments.destroy',[$thread,$message])}}" onsubmit="return confirm('Permanently delete this attachment?')">@csrf @method('DELETE')<button class="dropdown-item text-danger" type="submit">Delete attachment</button></form></li></ul></div></div><small class="text-muted">Client viewed: {{$message->client_viewed_at?->format('M j, Y g:i A') ?? 'Not yet'}} &middot; Downloaded: {{$message->attachment_downloaded_at?->format('M j, Y g:i A') ?? 'Not yet'}}</small>@elseif($message->sender_type==='admin')<small class="text-muted d-block mt-2">Client viewed: {{$message->client_viewed_at?->format('M j, Y g:i A') ?? 'Not yet'}}</small>@endif</article>@endforeach
<form method="post" action="{{route('admin.messages.reply',$thread)}}" enctype="multipart/form-data">@csrf<label class="form-label" for="body">Reply</label><textarea class="form-control" id="body" name="body" rows="4" maxlength="10000" required></textarea><label class="form-label mt-3" for="attachment">Attachment (optional)</label><input class="form-control" id="attachment" name="attachment" type="file" accept="application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png"><button class="btn btn-brand mt-3">Send reply</button></form>
</div>
<div class="border rounded p-3 mt-4 d-flex flex-wrap justify-content-between align-items-center gap-3"><div><strong>Email notification</strong><div class="text-muted small">Last sent: {{$thread->notification_last_sent_at?->format('M j, Y g:i A') ?? 'Not sent'}} &middot; Reminders: {{$thread->reminder_count}} &middot; Status: {{str($thread->notification_status ?? 'not sent')->title()}}</div></div><form method="post" action="{{route('admin.messages.remind',$thread)}}" onsubmit="return confirm('Send another email reminder that a secure message is waiting?')">@csrf<button class="btn btn-outline-brand" @disabled(blank($thread->client->email))>Send email reminder</button></form></div>
</div></section>
@endsection
